#!/usr/bin/env bash
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
function Purpose() {
# begin block comment =============================
: <<'END'

#  Purpose:  tar the current folder and give the archive a useful name..

chmod +x ~/bin/tarc4

END
# end block comment ===============================
}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#cd ; 
date ; set +vx  ; set -vx ; # echo off, then echo on
#
dts=$(date +"__%Y.%m.%d_%H.%M.%S")

# mkdir -p tmp/dglog
mv log/development.log log/development.log.$(date +"__%Y.%m.%d_%H.%M.%S").log

# The following 2 commands are optional - they keep your git repo in good shape.
# git prune --progress # delete all the objects w/o references
# git gc --aggressive # aggressively collect garbage; may take a lot of time on large repos

###### tar current folder..
base=$(basename $PWD);export HOSTNAME;
curfolder=${PWD##*/}
echo 45456
echo base=$base    hostname=$HOSTNAME  curfolder=$curfolder

#
# override base
#
bdir=ap
base=cisi543-b-yard

bkdir="/$bdir/backups"

# cd /$bdir
mkdir -p $bkdir



tar1() {

    # cd ..

    # doesn't work on mac osx
    #tar -czf $base-$HOSTNAME$(date +"__%Y.%m.%d_%H.%M.%S").tgz  $base --exclude={$base/tmp,$base/vendor/assets/javascripts,$base/shared,$base/public/assets,$base/nbproject,$base/log};cd $base

    # get the current path and replace / with _
    fnpath="${PWD////_}" ; echo $fnpath

    # OSX, have to have options first, then -f filename.tgz and source files 
    # tar -cz \
      # --exclude={$base/tmp,$base/vendor/assets/javascripts,$base/shared,$base/deployed,$base/public/assets,$base/nbproject,$base/log,$base/templates_c,$base/tar,node_modules,*.tgz,.hoodie/client.js} \
      # -f $base-$HOSTNAME$fnpath$(date +"__%Y.%m.%d_%H.%M.%S").tgz $base;cd $base
      
    # this one excludes any folder named.. datasys/ data/


 
    tarf() {
      #
      # notice the grep exclude list. Check to see nothing important is excluded.
      # 
      tfile=/$bdir/tmp-file-find-for-tar_${USER}_2324.txt; 
      find /$bdir/$base -type f |  grep -Ev  \
        'data/|sysdata/|public/assets/|/x/|.tgz|log/|tmp/|certs/|node_modules' > $tfile
      # Careful, the above excludes any data string|folder..
      # cat $tfile

      # add structure dump..
      find /$bdir/$base -type f |grep cisi_struc_mysqldump.sql >> $tfile
      
      tar -czf $bkdir/$base-$HOSTNAME$fnpath$dts.tgz -T $tfile
    }


    tarf

    cp -a /ap/cisi543-b-yard/data/mydat/t1/cisi_mysqldump_typ1.sql /ap/backups


}



# dump the database
cd /$bdir/$base/cisi543b
make dump

tar1


#
date
#
set +vx

